# Site settings
title: Carsten Bleek
description: 'Business Card Page'
url: 'https://cbleek.github.io'
baseurl: '/DigitalChange'
profilepic: '/images/cbleek.jpeg'
bkimage: '/images/ich2.jpeg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Carsten Bleek'
  email: carsten@bleek.org
  twitter_username: thomzuehlke
  facebook_username: Telefonanlage
  github_username:  cbleek
  linkedin_username:  cbleek
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
